"""All Pydantic/dataclass models for the entire system."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class RequirementType(str, Enum):
    FEATURE = "feature"
    CONSTRAINT = "constraint"
    DATA_MODEL = "data_model"
    API_CHANGE = "api_change"
    BEHAVIOUR = "behaviour"


class RequirementStatus(str, Enum):
    FULLY_EXISTS = "FULLY_EXISTS"
    PARTIALLY_EXISTS = "PARTIALLY_EXISTS"
    MISSING = "MISSING"
    CONFLICTED = "CONFLICTED"


class Requirement(BaseModel):
    id: str
    description: str
    requirement_type: RequirementType
    priority: Literal["high", "medium", "low"]
    raw_text: str


class SearchResult(BaseModel):
    file_path: str
    chunk_type: str
    name: str
    start_line: int
    end_line: int
    similarity_score: float
    content: str


class ConflictResult(BaseModel):
    affected_files: list[str]
    conflict_severity: Literal["high", "medium", "low"]
    explanation: str


class RequirementAnalysis(BaseModel):
    requirement: Requirement
    status: RequirementStatus
    matched_files: list[str]
    matched_functions: list[str]
    conflict_details: ConflictResult | None = None
    classification_reason: str


class EdgeCase(BaseModel):
    description: str
    related_requirement_id: str | None = None
    severity: Literal["must_discuss", "should_discuss"]


class DataModel(BaseModel):
    name: str
    description: str
    fields: list[str]
    is_new: bool


class APIChange(BaseModel):
    endpoint: str
    method: str
    description: str
    is_new: bool


class IndexResult(BaseModel):
    files_indexed: int
    chunks_created: int
    files_skipped: int
    duration_seconds: float


class EffortEstimate(BaseModel):
    conflict_resolution_hours: float
    extension_hours: float
    net_new_hours: float
    testing_hours: float
    total_days: float
    confidence: Literal["low", "medium", "high"]
    notes: str


class GapReport(BaseModel):
    spec_source: str
    reuse: list[RequirementAnalysis]
    extend: list[RequirementAnalysis]
    conflicts: list[RequirementAnalysis]
    net_new: list[RequirementAnalysis]
    edge_cases: list[EdgeCase]
    data_models: list[DataModel]
    api_changes: list[APIChange]
    implementation_order: list[str]
    effort_estimate: EffortEstimate
    generated_at: datetime = Field(default_factory=datetime.now)


# ---------------------------------------------------------------------------
# F3 — Repo Health Monitor models
# ---------------------------------------------------------------------------

class IssueComplexity(str, Enum):
    LOW = "low"       # 0 conflicts, ≤3 requirements
    MEDIUM = "medium" # 1-2 conflicts OR 4-6 requirements
    HIGH = "high"     # 3+ conflicts OR 7+ requirements OR 10+ files affected


class WatchedRepo(BaseModel):
    owner: str
    repo: str
    registered_at: datetime
    last_checked_at: datetime | None = None
    check_interval_minutes: int = 30
    is_active: bool = True
    issue_filters: list[str] = []


class WatcherAnalysis(BaseModel):
    """Lightweight analysis stored per issue by the watcher."""
    owner: str
    repo: str
    issue_number: int
    issue_title: str
    issue_url: str
    analysed_at: datetime
    requirements_count: int
    conflicts_count: int
    complexity: IssueComplexity
    touched_files: list[str]
    conflicted_files: list[str]
    requirement_summaries: list[dict]
    full_report_available: bool = False


class CrossIssueConflict(BaseModel):
    """A file touched by two or more open issues simultaneously."""
    file_path: str
    issue_numbers: list[int]
    issue_titles: dict[int, str]
    severity: Literal["high", "medium", "low"]
    detected_at: datetime


class WatchHealthReport(BaseModel):
    """The full health report generated by a watcher check run."""
    owner: str
    repo: str
    check_run_at: datetime
    new_issues_count: int
    new_analyses: list[WatcherAnalysis]
    cross_issue_conflicts: list[CrossIssueConflict]
    total_watched_issues: int
    next_check_at: datetime | None = None


# ---------------------------------------------------------------------------
# Phase 1+ — Agent harness models
# ---------------------------------------------------------------------------

class ToolCall(BaseModel):
    """A single tool invocation by the agent."""
    tool_name: str
    args: dict[str, Any]
    call_id: str = ""


class ToolResult(BaseModel):
    """The result of a tool invocation."""
    tool_name: str
    call_id: str = ""
    success: bool
    output: Any = None
    error: str | None = None
    duration_ms: float = 0.0
    # Security gate result for file writes
    security_status: Literal["pass", "warn", "block"] | None = None
    security_issues: list[str] = []


class SessionEvent(BaseModel):
    """One recorded event in the agent's session journal (for undo)."""
    event_id: str
    event_type: Literal["tool_call", "file_write", "shell_exec", "user_message", "agent_message"]
    created_at: datetime = Field(default_factory=datetime.now)
    tool_call: ToolCall | None = None
    tool_result: ToolResult | None = None
    message: str | None = None
    # For file_write events — used by undo
    file_path: str | None = None
    content_before: str | None = None
    content_after: str | None = None


class TokenUsage(BaseModel):
    """Token and cost tracking for one model."""
    model: str
    provider: str
    input_tokens: int = 0
    output_tokens: int = 0
    estimated_cost_usd: float = 0.0


class AgentSession(BaseModel):
    """A persistent agent chat session."""
    session_id: str
    created_at: datetime = Field(default_factory=datetime.now)
    last_active_at: datetime = Field(default_factory=datetime.now)
    project_path: str
    repo_owner: str = ""
    repo_name: str = ""
    git_branch: str = ""
    task_description: str = ""
    # Compact structured knowledge built up during the session
    learned_facts: list[str] = []
    files_understood: dict[str, str] = {}
    # Token accounting
    token_usage: list[TokenUsage] = []
    total_cost_usd: float = 0.0
    # Journal of all events (tool calls, writes, messages) — enables undo
    events: list[SessionEvent] = []

